---
# tasks file for tester2

- name: Include client
  include: client.yml 
  when: run_nagios_client is defined 


- name: Include server
  include: server.yml 
  when: run_nagios_server is defined 

